### PR TITLE
Use conf file update for f1

### PR DESCRIPTION
**Pull request by saki92**
Added options to start gNB as CU and DU nodes. Also added option to run gNB and UE in phy-test mode.

### CODE REVIEW

**Comment by gabri94** [comment]
Hi Sakthi, why you made two separate `.conf` files for the CU and DU? Can we have a single base.conf and then we add the relevand option trough CLI parameters?

**Comment by saki92** [comment]
> Hi Sakthi, why you made two separate `.conf` files for the CU and DU? Can we have a single base.conf and then we add the relevand option trough CLI parameters?

I tried but it didn't work as expected. The way the config file is read is weird and not clear and I'm not sure if I could fix it. Looks like reading paramList from CLI is not working. It works only when its in config file.

**Comment by gabri94** [comment]
Yeah, I also saw some some weird behavior, but to have better consistency I'd avoid to have more than one base.conf file, (I'll delete the others). I'd suggest to do similarly as I did in `def subst_bindip`, maybe by generalizing that function. Otherwise you could create a temporary conf file in /tmp/ or /run/ that gets populated from the base.conf + the modifications you need.  Or if you have any other idea that would preserve a single base.conf file let's discuss about it.

**Comment by saki92** [comment]
> Yeah, I also saw some some weird behavior, but to have better consistency I'd avoid to have more than one base.conf file, (I'll delete the others). I'd suggest to do similarly as I did in `def subst_bindip`, maybe by generalizing that function. Otherwise you could create a temporary conf file in /tmp/ or /run/ that gets populated from the base.conf + the modifications you need. Or if you have any other idea that would preserve a single base.conf file let's discuss about it.

I tried that also but its not that simple for F1 case as we need to have/not have entire paramList. At least it requires more careful inclusion and deletion from base.conf which I'm not comfortable doing. So I gave up that attempt. 

Meanwhile we figure this out, I suggest two options

1. We can have the current changes in a separate branch as it is now and switch whenever we want to run F1.
2. We can use the config files already in OAI directory instead of base.conf

**Comment by gabri94** [comment]
I think we could simply have the whole paramList in the base.conf file with all the parameters commented out. Then you uncomment and adapt the relevant lines. That's what i'm already doing with some other parameters.

**Pull request merged**
